language: objective-c
osx_image: xcode10.1
env:
  matrix:
   - SCHEME='DictionaryDecoder' TEST_SDK=iphonesimulator12.1
   - SCHEME='DictionaryDecoder-macOS' TEST_SDK=macosx
script: xcodebuild -project DictionaryDecoder.xcodeproj -scheme $SCHEME -sdk $TEST_SDK test
