language: objective-c
osx_image: xcode10.1
jobs:  
  include:
    - stage: test
      name: iOS
      script: xcodebuild clean test -project DictionaryDecoder.xcodeproj -scheme DictionaryDecoder -sdk iphonesimulator12.1
    - stage: test
      name: macOS
      script: xcodebuild clean test -project DictionaryDecoder.xcodeproj -scheme DictionaryDecoder-macOS -sdk macosx
    - stage: test
      name: Swift PM
      script: swift package clean; swift test