language: objective-c
osx_image: xcode10.1
env:
  matrix:
   - SCRIPT='xcodebuild clean test -project DictionaryDecoder.xcodeproj -scheme DictionaryDecoder -sdk iphonesimulator12.1'
   - SCRIPT='xcodebuild clean test -project DictionaryDecoder.xcodeproj -scheme DictionaryDecoder-macOS -sdk macosx'
   - SCRIPT='swift test'
script: $SCRIPT
