language: objective-c
osx_image: xcode10.1
script:
	- xcodebuild -project DictionaryDecoder.xcodeproj -scheme "DictionaryDecoder" -sdk iphonesimulator12.1 test
	- xcodebuild -project DictionaryDecoder.xcodeproj -scheme "DictionaryDecoder-macOS" -sdk macosx test